version: '3.8'

services:
  wirebarly-db:
    image: mysql:8.0
    container_name: wirebarly-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wirebarly
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --transaction-isolation=READ-COMMITTED
    ports:
      - "7233:3306"
    networks:
      - wirebarly-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5

  wirebarly-app:
    build: .
    container_name: wirebarly-app
    ports:
      - "9091:9091"
    depends_on:
      wirebarly-db:
        condition: service_healthy
    networks:
      - wirebarly-net
    environment:
      SPRING_PROFILES_ACTIVE: docker

networks:
  wirebarly-net:
    driver: bridge
